# Generated by Django 5.1.1 on 2024-09-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_title_alter_post_likes_alter_post_shares_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
